---

- name: ansible module dependencies
  apt:
    package=python-psycopg2
    state=present

- name: package
  apt:
    package=graphite-web
    state=present

- name: config
  template:
    src=local_settings.py.j2
    dest=/etc/graphite/local_settings.py

- name: nginx config
  copy:
    src=nginx/graphite
    dest=/etc/nginx/sites-available/graphite
  notify: reload nginx

- name: nginx config symlink
  file:
    src=/etc/nginx/sites-available/graphite
    dest=/etc/nginx/sites-enabled/graphite
    state=link
  notify: reload nginx

- name: uwsgi config
  copy:
    src=uwsgi/graphite.ini
    dest=/etc/uwsgi/apps-available/graphite.ini
  notify: restart uwsgi

- name: uwsgi config symlink
  file:
    src=/etc/uwsgi/apps-available/graphite.ini
    dest=/etc/uwsgi/apps-enabled/graphite.ini
    state=link
  notify: restart uwsgi

- name: graphite wsgi symlink
  file:
    src=/usr/share/graphite-web/graphite.wsgi
    dest=/usr/share/graphite-web/wsgi.py
    state=link
  notify: restart uwsgi

- name: postgres db
  postgresql_db:
    name=graphite
  sudo_user: postgres

- name: postgres user
  postgresql_user:
    name=graphite
    password=graphite
    db=graphite
  sudo_user: postgres

- name: syncdb
  shell: graphite-manage syncdb
